# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 05bc2647bfe0864098d4d517e9080ab0f248f2f149d3bce2d1b70e76d553af978558b5e1b876f0d0d7c62cb779345ced0740a433cc5fd6671a34773c65bfe23e

test:
  secret_key_base: 6b7768db413a906ef9108e929c0e793b9eaa40d0d5d2ce1ad1bb43d634f1efd868b1635051ddf58b465348167707e86cf9704d0fe05835560def040d8fd6469d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
